### ISSUE TITLE
URL slug is used for <title> instead of actual title

### ISSUE THREAD

**Issue by auchenberg** [MicrosoftEdge/MicrosoftEdge-Documentation#23]
![developer-tools-keyboard-shortcuts - microsoft edge microsoft edge dev 2016-01-26 15-31-57](https://cloud.githubusercontent.com/assets/173559/12598888/02f6eefc-c442-11e5-8194-47a82a17a1ec.png)

Has consequences for SEO too:
![edge f12 developer tools keyboard shortcuts - google search 2016-01-26 15-33-48](https://cloud.githubusercontent.com/assets/173559/12598924/39cf2e12-c442-11e5-8796-2e8ecfa7c71e.png)

**Comment by mattwojo** [comment]
@molant ^ just wanted to make sure that you saw this.

**Comment by molant** [comment]
Yup, scheduled for the next sprint among other doc related stuff. Can you open this issue in the other repo as well? It is a problem with the website and not the documentation.
Thanks!

**Comment by mattwojo** [comment]
Sweet - yep, will do.

**Comment by mattwojo** [comment]
Oops - probably still want this open.

**Comment by molant** [comment]
Actually I was thinking about the website project :)

**Comment by mattwojo** [comment]
Website project?

**Comment by mattwojo** [comment]
Oh -- the repo where the HTML/CSS etc are located?  ...I don't have access to that.

**Comment by molant** [comment]
Yup, saw that. I just created the item there. Closing this one.
