### ISSUE TITLE
Update all instances of modern.ie to new website

### ISSUE THREAD

**Issue by molant** [MicrosoftEdge/MicrosoftEdge-Documentation#26]
@mattwojo it seems like there are still a couple instances of `modern.ie` in the documentation:
https://github.com/MicrosoftEdge/MicrosoftEdge-Documentation/search?utf8=%E2%9C%93&q=modern.ie

**Comment by mattwojo** [comment]
Blarg! Thanks @molant  -- updated these links.  *Should they be a rel link rather than hard-coded URL?

**Comment by molant** [comment]
probably hardcoded in case we need to put yet another redirect in case things change

**Comment by mattwojo** [comment]
Cool.
