### ISSUE TITLE
Dev Guide/What's new has broken links

### ISSUE THREAD

**Issue by BurtHarris** [MicrosoftEdge/MicrosoftEdge-Documentation#29]
Links to the following two topics on the [What's New](https://github.com/MicrosoftEdge/MicrosoftEdge-Documentation/tree/master/dev-guide) page are broken: 
* Updates to the Selection API  
* Web Notifications API 

It looks like this may be due to case-sensitivity issues, e.g. the Selection API URL in the markdown file is `./html5/selection-api`, it may need to be `./html5/selection-API` since GitHub is hosted on a case-sensitive server.

**Comment by abbycar** [comment]
Good catch! This is only an issue on GitHub. The live site is unaffected by casing in links. 
This should be fixed now.
https://github.com/MicrosoftEdge/MicrosoftEdge-Documentation/commit/861f409808a884ef8b933a1d25cafe94908a8cdd
