### ISSUE TITLE
F12: DOM Explorer missing tool descriptions 

### ISSUE THREAD

**Issue by libbymc** [MicrosoftEdge/MicrosoftEdge-Documentation#38]
Add missing tool descriptions on the [DOM Explorer ](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/f12-devtools-guide/dom-explorer/)page for the Select element, DOM element highlighting, and Color picker tools.

![image](https://cloud.githubusercontent.com/assets/6559526/16019739/7428f3a6-315f-11e6-895b-4607e2d7b569.png)

**Comment by erikadoyle** [comment]
Closing this out--I've captured the task in VSO.
