### ISSUE TITLE
Doc Suggestion: incorrect spelling in windows.getAll API description

### ISSUE THREAD

**Issue by dDarkLORD** [MicrosoftEdge/MicrosoftEdge-Documentation#50]
**window**.getAll({populate: true}) is missing tabs property.

should be **windows**.getAll or simply getAll

**Comment by abbycar** [comment]
Fixed. Thanks for the catch! https://github.com/MicrosoftEdge/MicrosoftEdge-Documentation/commit/977c318935ee3389fa2378b568bb4965d0a3f7bd
