### ISSUE TITLE
Doc Suggestion: API links are pointing to mozilla website and there it says "?" for Edge Compatibility

### ISSUE THREAD

**Issue by dDarkLORD** [MicrosoftEdge/MicrosoftEdge-Documentation#51]
API links should point to our documentation only

**Comment by wbamberg** [comment]
FWIW, I'm hoping in the near future to import the [compat data for Edge](https://github.com/MicrosoftEdge/MicrosoftEdge-Documentation/tree/master/extensions/API-support/supported-APIs) into the [compat data that MDN uses](https://github.com/mdn/browser-compat-data/blob/master/webextensions/browser-compat-data.json), as long as any possible licensing/permission/attribution issues can be resolved. Then those question marks would be fixed :).

**Comment by abbycar** [comment]
Good catch! We're working with @wbamberg on this. Stay tuned :)

**Comment by wbamberg** [comment]
@abbycar , I added Edge compat data to https://github.com/mdn/browser-compat-data yesterday. You can see it, for example, here:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

If you see any problems, I'd love to know (or raise issues at https://github.com/mdn/browser-compat-data).

I'd also like to do a similar thing for manifest.json keys - do you have manifest.json compat data for Edge?

We're also planning to improve the JSON schema that we're using for the data, partly to make it easier to contribute. 

Feel free to email me if you'd like to talk about any of that.

**Comment by abbycar** [comment]
Closing this as we're now in the swing of updating compatibility tables on MDN :)

Please reach out to us at our [new repo](https://github.com/MicrosoftDocs/edge-developer) if you spot any other issues/suggestions with the docs!
