### ISSUE TITLE
Doc Suggestion: Sample project for Edge extensions

### ISSUE THREAD

**Issue by ErikApption** [MicrosoftEdge/MicrosoftEdge-Documentation#54]
It would be helpful to provide a sample visual studio project to develop Edge extensions.

**Comment by abbycar** [comment]
Thanks for the suggestion! A getting started guide is in the works, so expect a sample project or two soon. :)

**Comment by abbycar** [comment]
@ErikApption we now have an Edge extensions [getting started guide](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/guides/creating-an-edge-extension/)! This points off to a couple MDN samples that you can walk through and highlights the Edge code differences. You should have two complete Edge extensions after following this guide. :) 

We're getting a handful of samples together to put in a repo soon in the mean time.
