### ISSUE TITLE
Styling color input pseudo-elements

### ISSUE THREAD

**Issue by madcampos** [MicrosoftEdge/MicrosoftEdge-Documentation#57]
As in other browsers we can control, with browser prefixes, the appearance of the input with the following pseudo-element.
```css
input[type=color]::-webkit-color-swatch
input[type=color]::-webkit-color-swatch-wrapper
input[type=color]::-moz-color-swatch
input[type=color]::-moz-focus-inner
```
Still, there is no documentation of a way to do the same in Edge.
Is there any way or it's impossible to style the element?

**Comment by libbymc** [comment]
Edge does not implement this functionality at the moment, but I've passed this along to the team. Thanks for reaching out!
