### ISSUE TITLE
Problem about scroll tab list backward/forward

### ISSUE THREAD

**Issue by wilsonlym** [MicrosoftEdge/MicrosoftEdge-Documentation#60]
I had a problem about scroll tab list backward/forward in edge here. As we know, If we open many tabs, two buttons named scroll tab list backward and forward will appear to help us find those hidden tabs. But one strange thing is that scroll tab list backward/forward button can not be clicked twice in a row, which means we have to click the other button before clicking the right button. Let me show you the problem more specifically:
Firstly you may open many new tabs and click the scroll tab list forward to reach the rightest of the tabs, then use right click to choose "open the new tab" in any open tab. Here comes the problem that some tabs are hidden because of the newly opened tab but we are not able to click scroll tab list forward button to reach them now. Despite the fact that we can click scroll tab list backward first and then click scroll tab list forward, it is really annoying ; )
I have found this problem since last Oct, when I got my surface pro 4, so I am wondering now whether this will be fixed?

**Comment by molant** [comment]
Hi @wilsonlym,

thanks for taking the time but this repo is to report issues with the documentation available in developer.microsoft.com/en-us/microsoft-edge/platform/documentation/

To report issues with the browser you can use the feedback button in Microsoft Edge:
![image](https://cloud.githubusercontent.com/assets/606594/17909626/272aaa3c-693a-11e6-89c3-60e177e3f804.png).
