### ISSUE TITLE
Missing doc: DOM-Explorer pseudo-elements

### ISSUE THREAD

**Issue by marvinhagemeister** [MicrosoftEdge/MicrosoftEdge-Documentation#61]
There is no mention of pseudo elements (like `::before, ::after`) in the [Docs](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/f12-devtools-guide/dom-explorer/). Or is that something that the devtools do not support properly?

**Comment by erikadoyle** [comment]
In terms of being able to toggle different pseudo states (last section of the page), checkboxes are only available to toggle pseudo classes. In terms of general DOM Explorer support for pseudo elements, you can select a pseudo by selecting the parent element to which its 'content' is applied.
