### ISSUE TITLE
Cant use Web notification in edge mobile browsers?

### ISSUE THREAD

**Issue by whimsicaldreamer** [MicrosoftEdge/MicrosoftEdge-Documentation#62]
I am curious to know whether edge mobile browsers are supporting web notification api? I am using edge 14+. If it supports then a basic demo would be nice as there are no topics discussed anywhere on google.

**Comment by abbycar** [comment]
Hi @whimsicaldreamer!

At this point the web notification experience is not supported on mobile devices.  We are actively working on push notification support, which will allow notifications on our mobile devices. This is mentioned in the "What's Next" section of [this blog post](https://blogs.windows.com/msedgedev/2016/05/16/web-notifications-microsoft-edge/#attachment_16233). Without push notifications, the web page can’t post any notifications when the browser is in the background or when the webpage is on a background tab. If notifications can only be shown while the user is looking at the page in the foreground, that would be pretty limiting. :)

Keep a lookout for posts on our progress!
