### ISSUE TITLE
Wrong MSDN Link For Anchor Elements

### ISSUE THREAD

**Issue by bledwards1** [MicrosoftEdge/MicrosoftEdge-Documentation#67]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8246865/

Looks like the link **should** point here:
https://msdn.microsoft.com/en-us/library/ms535173(v=vs.85).aspx

But rather, points here:
https://msdn.microsoft.com/en-us/library/hh772391(v=vs.85).aspx

**Comment by erikadoyle** [comment]
Thanks for reporting this @bledwards1! Its looking like a more interesting bug than a simple data update, so might be symptomatic of a more widespread problem.

**Comment by bledwards1** [comment]
No problem at all. Once it is corrected please let me know so that I can update our Edge Issue Tracker (first link at the top of this).

**Comment by erikadoyle** [comment]
We have redirected the page in question (and the earlier way we were reporting the Edge API surface) to the [Edge API Catalog](https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/?page=1&q=edge:detected).
