### ISSUE TITLE
Is there a way to tell if an uncaught exception is thrown by an extension or the site?

### ISSUE THREAD

**Issue by xt0rted** [MicrosoftEdge/MicrosoftEdge-Documentation#73]
I realize this probably isn't the right place to ask this, but I haven't found anything on it so I wasn't sure if it was undocumented, unsupported, or I just didn't find it yet.

I have [Raygun](https://raygun.com) on my site to log uncaught exceptions. Last night I started getting one only on one of my devices and after some troubleshooting found that it's being triggered by the LastPass extension.

There's no details of the error being logged, but it only happens on forms when LastPass is running and includes the icon on supported fields. Turning off LastPass stops the error.

Since the error isn't related to my code I don't want to see this being reported but I'm unsure if there's a way to tell if the error in question originated from the site's code or an extension.

The full details of the logged error are in https://github.com/MindscapeHQ/raygun4js/issues/200

**Comment by scottlow** [comment]
If the exception is thrown from a content script that has been injected in the page, then F12 should correctly give the name of the script that's thrown the error. Extensions can (and often do) inject script directly in the page, however, and unfortunately, there is no way to determine the origin of an exception in this case aside from enabling extension developer features in about:flags and using F12 to break on all exceptions to catch the spot of origin.

There is also a bug in Edge where exceptions in content scripts will bubble up to the page context regardless of whether they are properly caught: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7698441/. We will be addressing this in a future update which should help reduce the number of exceptions that are caught using page-level logging.

Let me know if you have any other questions!
