### ISSUE TITLE
Documentation on Extension Development

### ISSUE THREAD

**Issue by codymullins** [MicrosoftEdge/MicrosoftEdge-Documentation#79]
It would be nice to have documented here clearly any information regarding extension development. Some searches don't yield too much - they only direct me to some API pages or back here to this documentation.

Is there a clear path if someone wanted to build extensions for edge or is this going to be kept locked down?

**Comment by abbycar** [comment]
@codymullins we have a new page on [creating your first Edge extension](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/guides/creating-an-edge-extension/). It links off to a few MDN examples and points out the minor tweaks to make it work with Edge. Once you've done that, you can refer to MDN for more development info. Comment back if this doesn't quite answer your question! :)

**Comment by codymullins** [comment]
@abbycar thanks, I think this is what I wanted.
