### ISSUE TITLE
More detail needed about packaging for enterprise

### ISSUE THREAD

**Issue by rjk** [MicrosoftEdge/MicrosoftEdge-Documentation#81]
Currently doc says 

> Instructions on packaging extensions are available through the Technology Adoption Program (TAP)

but there's no info or link about what this is and it's not easily searchable. How do enterprises sign up to this or how do ISVs become part of it? Who to contact?

**Comment by abbycar** [comment]
Hi @rjk!
Thanks for pointing this out. Now that packaging info is out, you can follow the normal [packaging guide](https://docs.microsoft.com/microsoft-edge/extensions/guides/packaging). I've updated the [enterprise extensions](https://docs.microsoft.com/microsoft-edge/extensions/extensions-for-enterprise) page with this info. :)

If you have other questions, please reach out at our [new repo](https://github.com/MicrosoftDocs/edge-developer).
