### ISSUE TITLE
Keyboard shortcuts page uses staging server URL

### ISSUE THREAD

**Issue by dstorey** [MicrosoftEdge/MicrosoftEdge-Documentation#9]
File: https://github.com/MicrosoftEdge/MicrosoftEdge-Documentation/blob/f0f8758fc161aa217e349adf1ab54a394f681bbe/f12-devtools-guide/developer-tools-keyboard-shortcuts/README.md

Uses the staging server URL rather than final public URL for the link with link text "the keyboard shortcuts for Internet Explorer versions 8, 9, and 10".

**Comment by dstorey** [comment]
CC/ @mattwojo

**Comment by mattwojo** [comment]
Good catch! Thanks @dstorey -- fixed. https://github.com/MicrosoftEdge/MicrosoftEdge-Documentation/commit/cdda00005a0fc38f3303a400bdb0be93a1e4ef83
